ARG BASE_IMAGE=intel/intel-extension-for-pytorch:2.5.0-xpu
FROM ${BASE_IMAGE} AS final

ARG COMMON_WORKDIR=/app

WORKDIR ${COMMON_WORKDIR}

# Step 1: Setup - Install system dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${COMMON_WORKDIR}/vllm-omni

# Step 2: Copy vllm-omni code and install
COPY . ${COMMON_WORKDIR}/vllm-omni
RUN cd ${COMMON_WORKDIR}/vllm-omni && pip install --no-cache-dir ".[dev]"

RUN ln -sf /usr/bin/python3 /usr/bin/python

CMD ["/bin/bash"]

ENTRYPOINT []

# Set entrypoint for vllm-openai official images
FROM final AS vllm-openai
ENTRYPOINT ["vllm", "serve", "--omni"]
